### PR TITLE
Fixed person add

### PR DESCRIPTION
**Pull request by un-tone**
For https://github.com/StarcounterApps/People/issues/86

### CODE REVIEW

**Comment by warpech** [comment]
@Loudness could you pls review, with a test if that fixes #86?

**Comment by warpech** [comment]
ping @Loudness

**Comment by Loudness** [comment]
Still getting error. 
Following the steps as explained above.
Steps to reproduce:

1. Start Launcher, SignIn, People and CompositionProvider (all develop branch) on an empty database
2. Go to localhost:8080/signin/generateadminuser to generate the admin user
3. Go to localhost:8080/launcher and sign in as admin/admin
4. Click on "Persons" in the left menu
5. Click on "Add person"
6. Type in the first name
7. Press "Save"

Pressing save renders the following error:

**Comment by Loudness** [comment]
For quicker retesting. 
Use following script in a .CMD file. (edit to your own custom path)
`
staradmin delete db
staradmin kill all

CALL C:\Starcounter\examples\Launcher\run.bat
CALL C:\Starcounter\newdev\SignIn\run.bat
CALL C:\Starcounter\newdev\peopleFresh\run.bat
CALL C:\Starcounter\newdev\CompositionProvider\run.bat

ECHO Generate admin user.
powershell -command "& {&"iwr 'http://localhost:8080/signin/generateadminuser'"}"

Echo Now got to http://localhost:8080/launcher
`

**Comment by un-tone** [comment]
@Loudness could you please double check it again? It works well on my side.

**Comment by warpech** [comment]
@habib535 could you pls do the review of this PR? Pls check if the code seems right and if you can verify that it fixes the issue. Thanks!

**Comment by Loudness** [comment]
Yes, please check it. I might have something installed that does not make it work correctly at the moment.

**Comment by habib535** [comment]
> Start Launcher, SignIn, People and CompositionProvider (all develop branch) on an empty database
This gives error
> Start Launcher, SignIn, CompositionProvider (develop branch) and **People (fix-person-add branch)** on an empty database
Works fine

Also the changes looks good to me!

**Comment by un-tone** [comment]
Thanks!

**Pull request merged**
