### PR TITLE
Update elements

### PR DESCRIPTION
**Pull request by Mihaiii**
For Starcounter/RebelsLounge#193 .

@bouguila Please check the changes and please update the CSS rules or tell me where should the new rules be inserted.

Also, how important is the date format?
With `Vaadim-date-picked` the displayed format was "MM/DD/YYYY", but the value in the view-model was "YYYY-MM-DD".
I let the format the one that was in data-model (`pikaday-decorator` displays whatever format I want, but when the value comes from the DB, it will be "YYYY-MM-DD", unless I really want to change it with JS).

### CODE REVIEW

**Comment by bouguila** [comment]
i personally think that it does not match 100% look&feel of the page. but we can keep it until we find a better suite.

**Comment by Mihaiii** [comment]
> i personally think that it does not match 100% look&feel of the page. but we can keep it until we find a better suite.

It definitely doesn't - that's why I asked about the updated CSS.

We really need to replace `vaadin-date-picker` at lease temporarily, like you said, and that fork is the best choice I have at the moment, unless you can find a hybrid custom element that will work (I tried multiple options, but couldn't find anything better than this that would work). About the label and the placeholder, I'll add them - the only thing I'm not sure of is where to add the CSS rules.

**Comment by Mihaiii** [comment]
Having a look similar with `vaadin-combo-box` (used in "Nationality") is tricky because I can't have `pikaday-decorator` inside `paper-input-container`. I will come back to it.

**Comment by Mihaiii** [comment]
@bouguila In order to keep a constant loop on the page and because we use `vaadin-combo-box`, I decided to use a specific version of `vaadin-combo-box`. When we will migrate to Polymer 2, we will use the latest. Please review this PR.

**Pull request merged**
