### PR TITLE
Search fix related to Stellar-crm/issues/6

### PR DESCRIPTION
**Pull request by habib535**
--Developed two seperate designs for search results i.e. One for Type-ahead dropdown instant search and second for searcl-all page
--Developed a new web component for search all
--Added two new polymer elements in the sys folder, paper-tabs & iron-pages
--Updated the search Handler to also accept the search type parameter

### CODE REVIEW

**Comment by warpech** [comment]
As discussed on the meeting today, this will not be directly merged yet. It needs further changes to conform to https://github.com/StarcounterApps/Search/issues/1. Good job nevertheless!

**Comment by warpech** [comment]
@habib535 will this PR still be needed for the Search app, or is that coming as a separate PR to People?

**Comment by habib535** [comment]
@warpech with the Search app we are heading towards a completely separate path so this PR is not valid anymore. I've a feeling though that we might need slight changes in People app at some point but that is not relevant here.

**Comment by warpech** [comment]
Thanks for the clarification. Closing for now, but not removing the branch yet

**Pull request closed without merging**
