### PR TITLE
Update custom elements

### PR DESCRIPTION
**Pull request by Mihaiii**
For Starcounter/RebelsLounge#193

### CODE REVIEW

**Comment by Mihaiii** [comment]
The latest commit consists in a update of `bower.json` - all dependencies would use latest version in case there would be no conflicts.
But at `bower update` I get `ECONFLICT Unable to find suitable version for paper-styles`. Therefore, at this moment, I don't think that a merge should contain the latest commit.

**Comment by Mihaiii** [comment]
@bouguila Please don't release a new version that includes this merge (wasn't suppose to be merged until we discuss the issue related with the conflicts). Or, if you really want to release a version that includes these changes, please undo https://github.com/StarcounterApps/People/pull/137/commits/e49c76f5e008b5ed39bf9ba2bae0444bb0439b22

**Comment by bouguila** [comment]
@Mihaiii sorry i thought it it fine to merge. i have reverted back the changes.

**Comment by warpech** [comment]
@Mihaiii will you make a new PR? I can be the reviewer, unless you'd like to assign @bouguila.

**Comment by warpech** [comment]
> But at bower update I get ECONFLICT Unable to find suitable version for paper-styles. Therefore, at this moment, I don't think that a merge should contain the latest commit.

My advice is to cleanup the `sys` directory and do a clean `bower install`. Do you get an error then?

See the page https://github.com/Starcounter/Guidelines/blob/master/bower.md. Expecially the last paragraph.

> Later edit: I have no error if I use vaadin-combo-box version v3.0.0-beta1 (current latest version), but it requirest Polymer 2 and won't work with 1.9.3.

As Starcounter does not have Polymer 2.0, how is it possible then that you have no error if you use vaadin-combo-box version v3.0.0-beta1?

**Comment by Mihaiii** [comment]
`vaadin-date-picker` doesn't have a hybrid version. It should be replaced with another element.

**Comment by Mihaiii** [comment]
https://github.com/bendavis78/paper-date-picker also doesn't have a hybrid version.
https://github.com/fooloomanzoo/datetime-picker does. I'll use it and test it and after that make another PR.

**Comment by Mihaiii** [comment]
github.com/fooloomanzoo/datetime-picker has in `bower.json` Polymer 1.9 - 2, but it doesn't work with Polymer 1.9.3.
I'll keep looking for hybrid elements, but let me know if you have any suggestions.

**Pull request merged**
