### PR TITLE
Fixed styles for complex fields on the Person edit page

### PR DESCRIPTION
**Pull request by un-tone**
For https://github.com/Starcounter/CompanyTrack/issues/315

### CODE REVIEW

**Comment by tomalec** [comment]
Maybe you can create `src/People/wwwroot/People/css/people-default-composition.css` put 
```css
.people-custom-info-relation-type-wrapper {		
     display: flex;		
     flex-direction: row;		
     align-items: baseline;		
 }
```
and import it in all those partials?

**Comment by un-tone** [comment]
Sure. Fixed.

**Comment by warpech** [comment]
@un-tone have you tested in Chrome, Firefox and Edge? If it works in all 3 browsers, then I think it can be merged.

**Comment by un-tone** [comment]
@warpech I tested in Chrome and Firefox. Unfortunately I don't have Edge installed.

**Pull request merged**
